site_name: Django Meilisearch
repo_url: https://github.com/Lucashcr/django_meilisearch

theme:
  name: material  # Tema (recomendo o Material for MkDocs)
#  logo: images/logo.png  # Opcional, seu logotipo

nav:
  - Home: index.md
  - Installation: installation.md
  - Configuration: configuration.md
  - Basic Usage: basic_usage.md
  - Advanced Features: advanced_features.md
  - Contributing: contributing.md
  - License: license.md

markdown_extensions:
  - toc
  - tables
  - admonition  # Para notas, avisos, etc.
  - codehilite  # Realce de sintaxe em blocos de código
  - pymdownx.superfences  # Suporte para múltiplos blocos de código
  - pymdownx.tabbed  # Abas para organizar conteúdo

# extra_css:
#   - css/custom.css  # Arquivo de CSS customizado (opcional)

# extra_javascript:
#   - js/custom.js  # Arquivo de JS customizado (opcional)
