class MissingRequiredFieldError(Exception): ...
class CreateIndexError(Exception): ...
class InvalidIndexNameError(Exception): ...
class InvalidDjangoModelError(Exception): ...
class InvalidPrimaryKeyError(Exception): ...
class InvalidSearchableFieldError(Exception): ...
class InvalidFilterableFieldError(Exception): ...