name: Django Meilisearch CI
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]


jobs:
  Code-Checking:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2

      - name: Install dependencies
        run: poetry install

      - name: Run black
        run: poetry run black --check src

      - name: Run pylint
        run: poetry run pylint src
        env:
          MEILISEARCH_URL: "http://localhost:7700"
          MEILISEARCH_API_KEY: "meilimasterkey"

  Run-Tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ '3.9', '3.10', '3.11', '3.12', '3.13', '3.14' ]
        meilisearch-version: ['v1.9', 'v1.10', 'v1.11', 'v1.12', 'v1.13', 'v1.14', 'v1.15', 'v1.16', 'v1.17', 'v1.18', 'v1.19', 'v1.20', 'v1.21', 'v1.22', 'v1.23', 'v1.24']

    services:
      meilisearch:
        image: getmeili/meilisearch:${{ matrix.meilisearch-version }}
        ports:
          - "7700:7700"
        env:
          MEILI_MASTER_KEY: "meilimasterkey"
          MEILI_NO_ANALYTICS: true

    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2

      - name: Install dependencies
        run: poetry install

      - name: Run tests
        env:
          SECRET_KEY: "secret-key"
          DEBUG: False
          DATABASE_URL: "postgres://postgres:postgres@localhost:5432/postgres"
          MEILISEARCH_URL: "http://localhost:7700"
          MEILISEARCH_API_KEY: "meilimasterkey"
        run: poetry run pytest
